import './globals.css'
import Nav from './components/Nav.jsx'
import Providers from './providers'

export const metadata = {
  title: 'Stephen Tao',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className='min-h-screen bg-snowstorm-2 dark:bg-polarnight-4'>
        <Providers>
          <section className='flex flex-col items-center'>
            <Nav></Nav>
          </section>
          {children}
        </Providers>

      </body>
    </html>
  )
}
